CREATE DATABASE [UnitData]

use UnitData
ALTER DATABASE [UnitData] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UnitData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UnitData] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UnitData] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UnitData] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UnitData] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UnitData] SET ARITHABORT OFF 
GO
ALTER DATABASE [UnitData] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UnitData] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UnitData] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UnitData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UnitData] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UnitData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UnitData] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UnitData] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UnitData] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UnitData] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UnitData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UnitData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UnitData] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UnitData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UnitData] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UnitData] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UnitData] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UnitData] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [UnitData] SET  MULTI_USER 
GO
ALTER DATABASE [UnitData] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UnitData] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UnitData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UnitData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UnitData] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UnitData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [UnitData] SET QUERY_STORE = OFF
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Units](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[type] [varchar](50) NULL,
	[rates] [decimal](18, 3) NULL
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Units] ON 
GO
INSERT [dbo].[Units] ([id], [type], [rates]) VALUES (1, N'centimetersToInches', CAST(2.540 AS Decimal(18, 3)))
GO
INSERT [dbo].[Units] ([id], [type], [rates]) VALUES (2, N'inchesToCentimeteres', CAST(2.540 AS Decimal(18, 3)))
GO
SET IDENTITY_INSERT [dbo].[Units] OFF
GO
USE [master]
GO
ALTER DATABASE [UnitData] SET  READ_WRITE 
GO


